"""adds special moves and overdrives table

Revision ID: 0749ede18770
Revises: 71bbada072da
Create Date: 2025-01-17 17:20:17.424904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0749ede18770'
down_revision: Union[str, None] = '71bbada072da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overdrive_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('damage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guard', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('startup', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recovery', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('on_block', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('on_hit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('counter_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invuln', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risc_gain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risc_loss', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overdrive_moves_character'), 'overdrive_moves', ['character'], unique=False)
    op.create_index(op.f('ix_overdrive_moves_table_name'), 'overdrive_moves', ['table_name'], unique=False)
    op.create_index(op.f('ix_overdrive_moves_table_type'), 'overdrive_moves', ['table_type'], unique=False)
    op.create_table('special_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('damage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guard', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('startup', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recovery', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('on_block', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('on_hit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('counter_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invuln', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risc_gain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risc_loss', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_moves_character'), 'special_moves', ['character'], unique=False)
    op.create_index(op.f('ix_special_moves_table_name'), 'special_moves', ['table_name'], unique=False)
    op.create_index(op.f('ix_special_moves_table_type'), 'special_moves', ['table_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_special_moves_table_type'), table_name='special_moves')
    op.drop_index(op.f('ix_special_moves_table_name'), table_name='special_moves')
    op.drop_index(op.f('ix_special_moves_character'), table_name='special_moves')
    op.drop_table('special_moves')
    op.drop_index(op.f('ix_overdrive_moves_table_type'), table_name='overdrive_moves')
    op.drop_index(op.f('ix_overdrive_moves_table_name'), table_name='overdrive_moves')
    op.drop_index(op.f('ix_overdrive_moves_character'), table_name='overdrive_moves')
    op.drop_table('overdrive_moves')
    # ### end Alembic commands ### 