"""normalized models

Revision ID: 23e6366c9f60
Revises: cbecba146f11
Create Date: 2025-01-17 15:53:58.126556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23e6366c9f60'
down_revision: Union[str, None] = 'cbecba146f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_specific_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_specific_tables_character'), 'character_specific_tables', ['character'], unique=False)
    op.create_index(op.f('ix_character_specific_tables_table_name'), 'character_specific_tables', ['table_name'], unique=False)
    op.create_index(op.f('ix_character_specific_tables_table_type'), 'character_specific_tables', ['table_type'], unique=False)
    op.create_table('gatling_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('p_moves', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k_moves', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('s_moves', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('h_moves', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('d_moves', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cancel_options', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gatling_tables_character'), 'gatling_tables', ['character'], unique=False)
    op.create_index(op.f('ix_gatling_tables_table_name'), 'gatling_tables', ['table_name'], unique=False)
    op.create_index(op.f('ix_gatling_tables_table_type'), 'gatling_tables', ['table_type'], unique=False)
    op.create_table('normal_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('p_moves', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('k_moves', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('s_moves', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('h_moves', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('d_moves', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cancel_options', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normal_moves_character'), 'normal_moves', ['character'], unique=False)
    op.create_index(op.f('ix_normal_moves_table_name'), 'normal_moves', ['table_name'], unique=False)
    op.create_index(op.f('ix_normal_moves_table_type'), 'normal_moves', ['table_type'], unique=False)
    op.create_table('system_core_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('defense', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guts', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risc_gain_modifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prejump', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backdash_duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backdash_invuln', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backdash_airborne', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('forward_dash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unique_movement_options', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('movement_tension_gain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_core_data_character'), 'system_core_data', ['character'], unique=False)
    op.create_index(op.f('ix_system_core_data_table_name'), 'system_core_data', ['table_name'], unique=False)
    op.create_index(op.f('ix_system_core_data_table_type'), 'system_core_data', ['table_type'], unique=False)
    op.create_table('system_jump_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('jump_duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('high_jump_duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jump_height', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('high_jump_height', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pre_instant_air_dash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('air_dash_duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('air_backdash_duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('air_dash_distance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('air_backdash_distance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jumping_tension_gain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('air_dash_tension_gain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_jump_data_character'), 'system_jump_data', ['character'], unique=False)
    op.create_index(op.f('ix_system_jump_data_table_name'), 'system_jump_data', ['table_name'], unique=False)
    op.create_index(op.f('ix_system_jump_data_table_type'), 'system_jump_data', ['table_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_jump_data_table_type'), table_name='system_jump_data')
    op.drop_index(op.f('ix_system_jump_data_table_name'), table_name='system_jump_data')
    op.drop_index(op.f('ix_system_jump_data_character'), table_name='system_jump_data')
    op.drop_table('system_jump_data')
    op.drop_index(op.f('ix_system_core_data_table_type'), table_name='system_core_data')
    op.drop_index(op.f('ix_system_core_data_table_name'), table_name='system_core_data')
    op.drop_index(op.f('ix_system_core_data_character'), table_name='system_core_data')
    op.drop_table('system_core_data')
    op.drop_index(op.f('ix_normal_moves_table_type'), table_name='normal_moves')
    op.drop_index(op.f('ix_normal_moves_table_name'), table_name='normal_moves')
    op.drop_index(op.f('ix_normal_moves_character'), table_name='normal_moves')
    op.drop_table('normal_moves')
    op.drop_index(op.f('ix_gatling_tables_table_type'), table_name='gatling_tables')
    op.drop_index(op.f('ix_gatling_tables_table_name'), table_name='gatling_tables')
    op.drop_index(op.f('ix_gatling_tables_character'), table_name='gatling_tables')
    op.drop_table('gatling_tables')
    op.drop_index(op.f('ix_character_specific_tables_table_type'), table_name='character_specific_tables')
    op.drop_index(op.f('ix_character_specific_tables_table_name'), table_name='character_specific_tables')
    op.drop_index(op.f('ix_character_specific_tables_character'), table_name='character_specific_tables')
    op.drop_table('character_specific_tables')
    # ### end Alembic commands ### 