"""normal and special moves updates

Revision ID: 71bbada072da
Revises: 6332248066be
Create Date: 2025-01-17 17:18:28.371140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71bbada072da'
down_revision: Union[str, None] = '6332248066be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gatling_tables', 'p_moves',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('gatling_tables', 'k_moves',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('gatling_tables', 's_moves',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('gatling_tables', 'h_moves',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('gatling_tables', 'd_moves',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('gatling_tables', 'cancel_options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.add_column('normal_moves', sa.Column('input', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('normal_moves', 'move_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normal_moves', sa.Column('move_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('normal_moves', 'input')
    op.alter_column('gatling_tables', 'cancel_options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('gatling_tables', 'd_moves',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('gatling_tables', 'h_moves',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('gatling_tables', 's_moves',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('gatling_tables', 'k_moves',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('gatling_tables', 'p_moves',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ### 